name: Deploy

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get short SHA
        uses: benjlevesque/short-sha@v3.0
        id: short-sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/k8s-demo:${{ steps.short-sha.outputs.sha }}

      - name: Install Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Kustomize set image
        run: |
          cd k8s/manifest
          kustomize edit set image sonthh98/k8s-demo:${{ steps.short-sha.outputs.sha }}

      - name: Commit and push Kustomization changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add k8s/manifest/kustomization.yaml
          git commit --am --no-edit
          git push -f
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# git commit -m "Update kustomize image to ${{ secrets.DOCKER_USERNAME }}/k8s-demo:${{ steps.short-sha.outputs.sha }}"
